spring:
   application:
      name: liteinventory
      
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:~/db/liteinventory
      username: sa
      password: 
      
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         
   h2:
      console:
         enabled: true
      
server:
   port: 9000
   