-- INITIAL DATA

-- JENIS BARANG
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('ATK', 'Alat Tulis Kantor');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('FC', 'Fotocopy');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('JLD', 'Penjilidan');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('MM', 'Makan dan Minum');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('ELE', 'Alat Listrik Dan Elektronik');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('BSH', 'Alat Kebersihan Dan Bahan Pembersih');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('BBM', 'Bahan Bakar Minyak');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('PLS', 'Pelumas');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('HBS', 'Peralatan Bangunan Pakai Habis');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('BBB', 'Bahan Baku Bangunan');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('PKL', 'Pakaian Kerja Lapangan');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('SKC', 'Suku Cadang');

-- WILAYAH
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('100', 'SUP Kab. Bandung');
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('101', 'SUP Kota Bandung');
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('102', 'SUP Kab Bandung Barat Dan Kota Cimahi');
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('103', 'SUP Subang I');
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('104', 'SUP Subang II');
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('105', 'SUP Purwakarta');
INSERT INTO WILAYAH (KD_WILAYAH, NAMA) VALUES ('106', 'SUP Karawang');

-- KEGIATAN
INSERT INTO KEGIATAN (KD_KEGIATAN, NAMA) VALUES ('A01', 'Administrasi Sarana Dan Prasarana perkantoran');
INSERT INTO KEGIATAN (KD_KEGIATAN, NAMA) VALUES ('A02', 'Pemeliharaan Sarana Dan prasarana Perkantoran');
INSERT INTO KEGIATAN (KD_KEGIATAN, NAMA) VALUES ('A03', 'Peningkatan Sarana Dan prasarana Perkantoran');
INSERT INTO KEGIATAN (KD_KEGIATAN, NAMA) VALUES ('A04', 'Pemeliharaan Jalan Dan Jembatan');
INSERT INTO KEGIATAN (KD_KEGIATAN, NAMA) VALUES ('A05', 'Peningkatan Jalan Dan Jembatan');
INSERT INTO KEGIATAN (KD_KEGIATAN, NAMA) VALUES ('A06', 'Rehabilitasi Jalan Dan Jembatan');