-- INITIAL DATA

-- PERUSAHAAN
INSERT INTO PERUSAHAAN (ID_PERUSAHAAN, NAMA, STATUS) VALUES ('GOV022000001', 'PU', 'A');

-- JENIS BARANG
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('ATK', 'Alat Tulis Kantor');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('FC', 'Fotocopy');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('JLD', 'Penjilidan');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('MM', 'Makan dan Minum');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('ELE', 'Alat Listrik Dan Elektronik');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('BSH', 'Alat Kebersihan Dan Bahan Pembersih');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('BBM', 'Bahan Bakar Minyak');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('PLS', 'Pelumas');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('HBS', 'Peralatan Bangunan Pakai Habis');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('BBB', 'Bahan Baku Bangunan');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('PKL', 'Pakaian Kerja Lapangan');
INSERT INTO KATEGORI_BARANG (KD_KATEGORI, NAMA) VALUES ('SKC', 'Suku Cadang');

-- SATUAN
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('PCE', 'Buah');
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('LTR', 'Liter');
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('BOX', 'Dus');
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('KGM', 'Kilogram');
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('LSN', 'Lusin');
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('RIM', 'Rim');
INSERT INTO SATUAN (KD_SATUAN, NAMA) VALUES ('PKG', 'Pak');

-- WILAYAH
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('100', 'GOV022000001', 'SUP Kab. Bandung');
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('101', 'GOV022000001', 'SUP Kota Bandung');
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('102', 'GOV022000001', 'SUP Kab Bandung Barat Dan Kota Cimahi');
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('103', 'GOV022000001', 'SUP Subang I');
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('104', 'GOV022000001', 'SUP Subang II');
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('105', 'GOV022000001', 'SUP Purwakarta');
INSERT INTO WILAYAH (KD_WILAYAH, ID_PERUSAHAAN, NAMA) VALUES ('106', 'GOV022000001', 'SUP Karawang');

-- KEGIATAN
INSERT INTO KEGIATAN (KD_KEGIATAN, ID_PERUSAHAAN, NAMA) VALUES ('A01', 'GOV022000001', 'Administrasi Sarana Dan Prasarana perkantoran');
INSERT INTO KEGIATAN (KD_KEGIATAN, ID_PERUSAHAAN, NAMA) VALUES ('A02', 'GOV022000001', 'Pemeliharaan Sarana Dan prasarana Perkantoran');
INSERT INTO KEGIATAN (KD_KEGIATAN, ID_PERUSAHAAN, NAMA) VALUES ('A03', 'GOV022000001', 'Peningkatan Sarana Dan prasarana Perkantoran');
INSERT INTO KEGIATAN (KD_KEGIATAN, ID_PERUSAHAAN, NAMA) VALUES ('A04', 'GOV022000001', 'Pemeliharaan Jalan Dan Jembatan');
INSERT INTO KEGIATAN (KD_KEGIATAN, ID_PERUSAHAAN, NAMA) VALUES ('A05', 'GOV022000001', 'Peningkatan Jalan Dan Jembatan');
INSERT INTO KEGIATAN (KD_KEGIATAN, ID_PERUSAHAAN, NAMA) VALUES ('A06', 'GOV022000001', 'Rehabilitasi Jalan Dan Jembatan');